info_receitas/bolos/urls.py
from django.urls import path

from . import views

app_name = "bolos"
urlpatterns = [
    path('', views.index, name='index'),
    path('chocolate', views.chocolate, name='chocolate'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

info_receitas/info_receitas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bolos/', include('bolos.urls')),
    path('receitas/', include('receitas.urls'))

]

info_receitas/receitas/urls.py
from django.urls import path

from . import views

app_name = "receitas"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:receita_id>/', views.editar_receita, name='editar_receita'),
    path('gravar_receita', views.gravar_receita, name='gravar_receita'),
    path('<int:receita_id>/atualizar', views.atualizar_receita, name='atualizar_receita'),
    path('criar_receita', views.criar_receita, name='criar_receita'),
    path('<int:receita_id>/deletar', views.deletar_receita, name='deletar_receita'),
]

info_receitas/bolos/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

info_receitas/receitas/models.py
from django.db import models

class Receitas(models.Model):
    nome_receita = models.CharField(max_length=200)
    ingredientes = models.CharField(max_length=1000)
    def __str__(self):
        return self.nome_receita

info_receitas/bolos/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import Choice, Question
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'bolos/index.html', context)

def chocolate(request):
    return HttpResponse("Pagina de chocolates")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'bolos/detail.html', {'question': question})
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'bolos/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'bolos/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('bolos:results', args=(question.id,)))

info_receitas/receitas/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import Receitas
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

def index(request):
    receitas = Receitas.objects.all()
    return render(request, 'receitas/index.html', {'receitas' : receitas})

def gravar_receita(request):
    nome_receita = request.POST['nome_receita']
    ingredientes = request.POST['ingredientes']
    inserir = Receitas(nome_receita=nome_receita,ingredientes=ingredientes )
    inserir.save()
    return HttpResponseRedirect(reverse('receitas:index'))
    
def editar_receita(request, receita_id):
    receita = get_object_or_404(Receitas, pk=receita_id)
    return render(request, 'receitas/editar.html', {'receita': receita})

def criar_receita(request):
    return render(request, 'receitas/gravar.html')

def atualizar_receita(request, receita_id):
    receita = get_object_or_404(Receitas, pk=receita_id)
    ingredientes = request.POST['ingredientes']
    receita.ingredientes = ingredientes
    receita.save()
    return HttpResponseRedirect(reverse('receitas:index'))

def deletar_receita(request, receita_id):
    receita = get_object_or_404(Receitas, pk=receita_id)
    receita.delete()
    return HttpResponseRedirect(reverse('receitas:index'))

info_receitas/bolos/templates/bolos/detail.html
<form action="{% url 'bolos:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

info_receitas/bolos/templates/bolos/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

info_receitas/bolos/templates/bolos/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'bolos:detail' question.id %}">Vote again?</a>

info_receitas/receitas/templates/receitas/editar.html
<form action="{% url 'receitas:atualizar_receita' receita.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Receita: {{ receita.nome_receita }}</h1></legend>
        <legend><h1>Ingredientes:</h1></legend>    
        <textarea id="ingredientes" name="ingredientes" 
            rows="5" cols="33">
            {{ receita.ingredientes }}
        </textarea>
    </fieldset>
    <input type="submit" value="Editar">
</form>

<button onclick="location.href='{% url 'receitas:deletar_receita' receita.id %}'">Deletar receita</button>

info_receitas/receitas/templates/receitas/gravar.html
<form action="{% url 'receitas:gravar_receita' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Digite o nome da receita:</h1></legend>
            <input type="text" name="nome_receita" id="nome_receita">
        <legend><h1>Digite os ingredientes:</h1></legend>    
        <textarea id="ingredientes" name="ingredientes"
            rows="5" cols="33">
        </textarea>
    </fieldset>
    <input type="submit" value="Gravar">
</form>

info_receitas/receitas/templates/receitas/index.html
<h1>Receitas</h1>
{% if receitas %}
    <ul>
    {% for receita in receitas %}
    <li><a href="{% url 'receitas:editar_receita' receita.id %}">{{ receita.nome_receita }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nenhuma receita cadastrada.</p>
{% endif %}

<button onclick="location.href='{% url 'receitas:criar_receita' %}'">Criar receita</button>